# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Runner' do
 use_frameworks!

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end